# base image elixer to start with
FROM elixir:1.7.3
ARG MIX_ENV=test

# install hex package manager
RUN mix local.hex --force

# install phoenix
RUN mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez --force
RUN apt update && apt install -y build-essential gcc

# create app folder
RUN mkdir /app
COPY . /app
WORKDIR /app

# setting the port and the environment (prod = PRODUCTION!)
ENV PORT=4000

# install dependencies (production only)
RUN mix local.rebar --force
RUN mix deps.get 
RUN cd deps/bcrypt_elixir && make clean && make
RUN mix compile
RUN mix test